
from enum import Enum

class StudentExcelHeaders(str, Enum):
    LAST_NAME = "APELLIDOS"
    FIRST_NAME = "NOMBRES"
    CI = "CARNET DE IDENTIDAD"
    EXPEDITO_CI = "EXPEDIDO EN"
    COMPLEMENTO = "COMPLEMENTO"
    BIRTHDATE = "FECHA DE NACIMIENTO"
    SCHOOL = "COLEGIO"
    COURSE = "CURSO"
    DEPARTMENT = "DEPARTAMENTO"
    PROVINCE = "PROVINCIA"
    EMAIL = "CORREO ELECTRONICO"
