colegios_santa_cruz = {
    1: "Colegio Saint George",
    2: "Colegio Británico",
    3: "Colegio Franco Boliviano",
    4: "Colegio Domingo Savio",
    5: "Colegio Alemán",
    6: "Colegio Uboldi",
    7: "Colegio La Salle",
    8: "Colegio Santa Ana",
    9: "Colegio Cambridge",
    10: "Colegio San Agustín",
    11: "Colegio Bautista Boliviano Brasileño",
    12: "Colegio Boliviano Americano",
    13: "Colegio Cardenal Cushing",
    14: "Colegio Centro Boliviano Japonés",
    15: "Colegio Espíritu Santo",
    16: "Colegio Isabel Saavedra",
    17: "Colegio Cristo Rey",
    18: "Colegio Libertador Simón Bolívar",
    19: "Colegio Santa Claudina Thevenet",
    20: "Colegio María Teresa Pulido",
    21: "Colegio América",
    22: "Colegio Renata Preto de Brunelli",
    23: "Colegio Carlos Laborde Pulido",
    24: "Colegio Normandía Thevenet",
    25: "Colegio Tipoy",
    26: "Colegio Comunidad Cristiana",
    27: "Colegio Juana Azurduy de Padilla",
    28: "Colegio Jesús María José",
    29: "Colegio Madre Clara Ricci",
    30: "Colegio María Francisca",
    31: "Colegio Félix Bascopé Gonzales",
    32: "Colegio Sor María Cristina Pérez",
    33: "Colegio Santa Cruz Cooperative School",
    34: "Colegio Mayor San Pablo",
    35: "Colegio Saint Thomas College",
    36: "Colegio Evangélico Buenas Nuevas",
    37: "Colegio Particular Emanuel",
    38: "Colegio Evangélico Bethesda",
    39: "Colegio Teach Mont",
    40: "Colegio Santa Mónica",
    41: "Colegio Nuestra Señora del Pilar",
    42: "Colegio Santiago",
    43: "Colegio Marcelino Champagnat",
    44: "Colegio Gabriel René Moreno",
    45: "Colegio Marista",
    46: "Colegio San José",
    47: "Colegio Sagrados Corazones",
    48: "Colegio San Antonio",
    49: "Colegio Buenas Nuevas",
    50: "Colegio Don Bosco"
}
