colegios_oruro = {
    1: "Unidad Educativa Simón Bolívar",
    2: "Unidad Educativa Colegio Alemán",
    3: "Unidad Educativa Don Bosco",
    4: "Unidad Educativa La Salle",
    5: "Unidad Educativa Anglo American School",
    6: "Unidad Educativa Antonio José de Sainz",
    7: "Unidad Educativa Juan Misael Saracho",
    8: "Unidad Educativa Oscar Alfaro",
    9: "Unidad Educativa Rodolfo Soria Galvarro",
    10: "Unidad Educativa 12 de Abril",
    11: "Unidad Educativa María Rosa Quiniela",
    12: "Unidad Educativa Carmen Guzmán de Mier",
    13: "Unidad Educativa Chiripujio",
    14: "Unidad Educativa Santa Rosa 2",
    15: "Unidad Educativa SMMP",
    16: "Unidad Educativa Oruro Ottawa",
    17: "Unidad Educativa COMIBOL Oruro 1",
    18: "Unidad Educativa COMIBOL Oruro 2",
    19: "Unidad Educativa Evangelico Filadelfia",
    20: "Unidad Educativa San Ignacio",
    21: "Unidad Educativa San Francisco",
    22: "Unidad Educativa San José",
    23: "Unidad Educativa San Martín",
    24: "Unidad Educativa Santa Rosa",
    25: "Unidad Educativa Santa Ana",
    26: "Unidad Educativa Santa María",
    27: "Unidad Educativa Santa Teresa",
    28: "Unidad Educativa Nueva Esperanza",
    29: "Unidad Educativa Nueva Vida",
    30: "Unidad Educativa Luz del Saber",
    31: "Unidad Educativa Luz y Verdad",
    32: "Unidad Educativa Fe y Alegría",
    33: "Unidad Educativa Esperanza",
    34: "Unidad Educativa Ángel María Limpias",
    35: "Unidad Educativa Ángela Pinckert",
    36: "Unidad Educativa Angelina Ribera",
    37: "Unidad Educativa Antofagasta",
    38: "Unidad Educativa Antonio Aguanari",
    39: "Unidad Educativa Antonio Bertha",
    40: "Unidad Educativa Antonio Vicente Seoane",
    41: "Unidad Educativa Aponte de Jorory",
    42: "Unidad Educativa Aponte de San Miguel",
    43: "Unidad Educativa Aponte de Usuri",
    44: "Unidad Educativa José Manuel Pando",
    45: "Unidad Educativa América",
    46: "Unidad Educativa Puerto Rico",
    47: "Unidad Educativa Villa Amazónica",
    48: "Unidad Educativa Juan Oliveira Barros",
    49: "Unidad Educativa 11 de Octubre",
    50: "Unidad Educativa El Saber"
}
